### ISSUE TITLE
Basic enum support

### ISSUE THREAD

**Issue by omnisci3nce** [ocaml-sys/ocaml-bindgen#2]
### Context

I extended the example to be

```c
typedef enum breed {
    Labrador,
    GoldenRetriever,
    Pug
} breed;
 
typedef struct Doggo {
    int many;
    breed breed;
    char wow;
} Doggo;
```
which generated the following ocaml in `doggo.ml`

```ocaml
type nonrec breed
type nonrec doggo = {
    many: int ;
    breed: breed ;
    wow: char }
```

### My Understanding

So as far as I can tell the enum type is just stubbed out for the purposes of getting an end-to-end example working and doesn't yet carry its fields in the IR.

Looking at 
```ocaml
 | Record of { rec_name : string; rec_fields : ir_field list }
 | Enum of { enum_name : string }
 ```
of the `ir_type`, it looks like what needs to be done is to add an additional field to the Enum record that contains a list of variants that we can then generate the stub code in OCaml for.

**Comment by omnisci3nce** [comment]
In my usage of C I've encountered a few usages of enums, standard usage where they start at 0 and increment each variant, ones where _just_ the first value is annotated with an integer (in binary or hex), and ones where each enum variant has an arbitrary assigned value (think opcodes or packet types in protocols).

For my first contribution I'm thinking of just trying to get the most basic usage working.

**Comment by leostera** [comment]
Hi @omnisci3nce! This is excellent. Thanks so much for opening the issue and the PR too 🙏🏼 –– I left a comment on #3, but otherwise I think it should be a great starting point.
