### ISSUE TITLE
Generate epoll bindings

### ISSUE THREAD

**Issue by leostera** [ocaml-sys/ocaml-bindgen#5]
Similar to #4, we need to generate EPoll bindings to be able to drop custom C code from `gluon`.

The syscalls we need are:

- [ ] Create an epoll instance with flags: `epoll_create1 : flags:int -> epoll`
- [ ] Await on an epoll instance: `epoll_wait : timeout:int64 -> max_events:int -> epoll -> event array`
- [ ] Configure an epoll instance: `epoll_ctl : epoll -> flags:int -> fd:Fd.t -> event -> unit`
- [ ] Reset an epoll instance: `epoll_ctl_null : epoll -> flags:int -> fd:Fd.t -> unit`

The C code we wrote for this lives [here](https://github.com/riot-ml/riot/blob/main/gluon/sys/unix/gluon_unix_epoll.c).

The generated does not need to match this 1-to-1, so some of the decision I made writing these bindings can be changed, no problem there.

**Comment by omnisci3nce** [comment]
I'm pretty keen to keep working on bindgen and this seems like a good a way as any to 'dogfood' (😂 ). I can begin working on this if that's okay. No doubt starting on this will spawn a bunch of smaller issues that get us closer one step at a time.

**Comment by omnisci3nce** [comment]
Could you expand on the `caml_enter_blocking_section` a tiny bit? I found the section https://v2.ocaml.org/manual/intfc.html on here that talks a bit about it and I *think* I get it but a little more context might save me wasting a bunch of time. I get the feeling we won't be able to intuit its necessity, if it indeed is necessary, purely from the `.h` header 🤔
